package com.vrockk.models.profile.user_profile

data class Profile(
    var __v: Int = 0,
    var _id: String = "",
    var address: String = "",
    var authToken: String = "",
    var bio: String = "",
    var countryCode: String = "",
    var createdAt: String = "",
    var deviceId: Any? = null,
    var deviceType: Any? = null,
    var dob: String = "",
    var email: String = "",
    var firstName: String = "",
    var followers: Int = 0,
    var following: Int = 0,
    var gender: String = "",
    var instagram: String = "",
    var isDeleted: Boolean = false,
    var isEmailVerified: Boolean = false,
    var isFollowing: Boolean = false,
    var isPhoneVerified: Boolean = false,
    var isSocialRegister: Boolean = false,
    var lastName: String = "",
    var password: String = "",
    var phone: String = "",
    var profilePic: String = "",
    var profileStatus: Int = 0,
    var provider: String = "",
    var providerId: String = "",
    var referingCode: String = "",
    var referralCode: String = "",
    var roles: String = "",
    var sendNoti: Int = 0,
    var status: Int = 0,
    var totalLikes: Int = 0,
    var totalPosts: Int = 0,
    var updatedAt: String = "",
    var userName: String = "",
    var wallet: Int = 0,
    var facebook: String = "",
    var youtube: String = ""
)