package com.vrockk.models.notification

data class User(
    val __v: Int,
    val _id: String,
    val address: String,
    val bio: String,
    val countryCode: String,
    val createdAt: String,
    val dob: String,
    val email: String,
    val firstName: String,
    val gender: String,
    val id: String,
    val instagram: String,
    val isDeleted: Boolean,
    val isEmailVerified: Boolean,
    val isPhoneVerified: Boolean,
    val isSocialRegister: Boolean,
    val lastName: String,
    val latitude: Double,
    val level: Int,
    val location: Location,
    val longitude: Double,
    val phone: String,
    val profilePic: String="",
    val profileStatus: Int,
    val provider: String,
    val providerId: String,
    val referingCode: String,
    val referralCode: String,
    val roles: String,
    val updatedAt: String,
    val userName: String="",
    var facebook: String = "",
    var youtube: String = ""
)