package com.vrockk.models.home.home_page

data class UserId(
    var __v: Int = 0,
    var _id: String = "",
    var authToken: String = "",
    var bio: String = "",
    var countryCode: String = "",
    var createdAt: String = "",
    var deviceId: String = "",
    var deviceType: String = "",
    var email: String = "",
    var firstName: String = "",
    var instagram: String = "",
    var isVerified: Boolean = false,
    var lastName: String = "",
    var password: String = "",
    var phone: String = "",
    var profilePic: String = "",
    var provider: String = "",
    var providerId: String = "",
    var referralCode: String = "",
    var sendNoti: Int = 0,
    var status: Int = 0,
    var updatedAt: String = "",
    var userName: String = "",
    var wallet: Int = 0,
    var facebook: String = "",
    var youtube: String = ""
)