package com.vrockk.models.block.blocklistuser

data class Blocked(
    var __v: Int = 0,
    var _id: String = "",
    var address: String = "",
    var bio: String = "",
    var countryCode: String = "",
    var createdAt: String = "",
    var dob: String = "",
    var email: String = "",
    var firstName: String = "",
    var gender: String = "",
    var id: String = "",
    var instagram: String = "",
    var isDeleted: Boolean = false,
    var isEmailVerified: Boolean = false,
    var isPhoneVerified: Boolean = false,
    var isSocialRegister: Boolean = false,
    var lastName: String = "",
    var phone: String = "",
    var profilePic: String = "",
    var profileStatus: Int = 0,
    var provider: String = "",
    var providerId: String = "",
    var referingCode: String = "",
    var referralCode: String = "",
    var roles: String = "",
    var updatedAt: String = "",
    var userName: String = "",
    var facebook: String = "",
    var youtube: String = ""
)