package com.vrockk.models.profile.following_list

data class Data(
    var __v: Int = 0,
    var _id: String = "",
    var authToken: String = "",
    var bio: String = "",
    var createdAt: String = "",
    var deviceId: Any? = null,
    var deviceType: Any? = null,
    var email: String = "",
    var firstName: String = "",
    var instagram: String = "",
    var isDeleted: Boolean = false,
    var isVerified: Boolean = false,
    var isFollowing: Boolean = false,
    var lastName: String = "",
    var password: String = "",
    var profilePic: String = "",
    var provider: String = "",
    var providerId: String = "",
    var referralCode: String = "",
    var roles: String = "",
    var sendNoti: Int = 0,
    var status: Int = 0,
    var updatedAt: String = "",
    var userName: String = "",
    var wallet: Int = 0,
    var facebook: String = "",
    var youtube: String = ""
)